In [ ]:
import numpy as np
import pandas as pd

In [20]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=["cgpa","profile_score","is_placed"])

In [21]:
df

,cgpa,profile_score,is_placed
0,8,8,1
1,7,9,1
2,6,10,0
3,5,5,0


In [22]:
def initilize_parameter(layer_dims):
    np.random.seed(3)
    parameters={}
    L = len(layer_dims)
    
    for l in range(1,L):
        parameters["W" + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters["b" + str(l)] = np.zeros((layer_dims[l], 1))

    return parameters
        

In [23]:
initilize_parameter([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [24]:
def sigmoid(Z):
    A = 1/(1+np.exp(-Z))
    
    return A

In [25]:
def linear_forward(A_prev,W,b):
    Z = np.dot(W.T,A_prev) + b
    return sigmoid(Z)

In [26]:
def L_layer_forward(X,parameters):
    
    A = X
    L = len(parameters)//2
    
    for l in range(1,L+1):
        A_prev = A
        Wl = parameters["W" + str(l)]
        bl = parameters["b" + str(l)]
        
        # print("A" + str(l-1) + ": ", A_prev )
        # print("W" + str(l) + ": ", Wl )
        # print("b" + str(l) + ": ", bl)
        # print("--"*20)
        A = linear_forward(A_prev,Wl,bl)
        # print("A" + str(l) + ": ", A)
        # print("**"*20)
        
    return A, A_prev

In [27]:
parameters = initilize_parameter([2,2,1])

In [28]:
X = df[["cgpa","profile_score"]].values[2].reshape(2,1)
y = df[["is_placed"]].values[2][0]

In [29]:
y_hat, A1 = L_layer_forward(X,parameters)

In [30]:
y_hat = y_hat[0][0]

In [31]:
A1

array([[0.83201839],
       [0.83201839]])

In [39]:
def loss_calculation(y,y_hat):
    return (-y * np.log(y_hat) - (1-y) * np.log(1 - y_hat))

In [40]:
loss_calculation(y,y_hat)

np.float64(0.8153491899439818)

In [34]:
def update_parameters(parameters,y,y_hat,A1,X, n):
    parameters["W1"][0][0] =  parameters["W1"][0][0] + (n * (y-y_hat) * parameters["W2"][0][0] * A1[0][0] * (1-A1[0][0]) * X[0][0])
    parameters["W1"][0][1] =  parameters["W1"][0][1] + (n * (y-y_hat) * parameters["W2"][0][0] * A1[0][0] * (1-A1[0][0]) * X[0][0])    
    parameters["b1"][0][0] =  parameters["b1"][0][0] + (n * (y-y_hat) * parameters["W2"][0][0] * A1[0][0] * (1-A1[0][0]))    
    
    parameters["W1"][1][0] =  parameters["W1"][1][0] + (n * (y-y_hat) * parameters["W2"][1][0] * A1[1][0] * (1-A1[1][0]) * X[0][0])
    parameters["W1"][1][1] =  parameters["W1"][1][1] + (n * (y-y_hat) * parameters["W2"][1][0] * A1[1][0] * (1-A1[1][0]) * X[1][0])    
    parameters["b1"][0][0] =  parameters["b1"][0][0] + (n * (y-y_hat) * parameters["W2"][1][0] * A1[1][0] * (1-A1[1][0]))  

    parameters["W2"][0][0] =  parameters["W2"][0][0] + (n * (y-y_hat) * A1[0][0])
    parameters["W2"][1][0] =  parameters["W2"][1][0] + (n * (y-y_hat) * A1[1][0])    
    parameters["b2"][0][0] =  parameters["W2"][1][0] + (n * (y-y_hat))    

In [41]:
update_parameters(parameters,y,y_hat,A1,X,0.01)

In [36]:
parameters

{'W1': array([[0.0995459 , 0.0995459 ],
        [0.0995459 , 0.09924317]]),
 'b1': array([[-0.00015137],
        [ 0.        ]]),
 'W2': array([[0.09549458],
        [0.09549458]]),
 'b2': array([[0.09007953]])}

In [43]:
# epoch implementation 


parameters = initilize_parameter([2,2,1])
epochs = 50


for i in range(epochs):
    Loss = []
    
    for j in range(df.shape[0]):
        X = df[["cgpa","profile_score"]].values[j].reshape(2,1)
        y = df[["is_placed"]].values[j][0]
        y_hat, A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]
        Loss.append(loss_calculation(y,y_hat))
        update_parameters(parameters,y,y_hat,A1,X,0.01)
    
    print("Epoch - ", i, "Loss - ", np.array(Loss).mean())  

Epoch -  0 Loss -  0.7122914596679644
Epoch -  1 Loss -  0.7014727579485711
Epoch -  2 Loss -  0.7012384647871388
Epoch -  3 Loss -  0.7010139766889188
Epoch -  4 Loss -  0.700798858277434
Epoch -  5 Loss -  0.7005926949283202
Epoch -  6 Loss -  0.7003950916908817
Epoch -  7 Loss -  0.7002056722712593
Epoch -  8 Loss -  0.7000240780731075
Epoch -  9 Loss -  0.69984996729229
Epoch -  10 Loss -  0.6996830140623198
Epoch -  11 Loss -  0.6995229076474754
Epoch -  12 Loss -  0.6993693516807112
Epoch -  13 Loss -  0.6992220634436692
Epoch -  14 Loss -  0.6990807731862589
Epoch -  15 Loss -  0.6989452234834397
Epoch -  16 Loss -  0.6988151686269866
Epoch -  17 Loss -  0.6986903740501565
Epoch -  18 Loss -  0.6985706157833117
Epoch -  19 Loss -  0.6984556799386711
Epoch -  20 Loss -  0.6983453622224818
Epoch -  21 Loss -  0.6982394674730087
Epoch -  22 Loss -  0.6981378092228383
Epoch -  23 Loss -  0.6980402092840932
Epoch -  24 Loss -  0.6979464973552341
Epoch -  25 Loss -  0.6978565106482153

In [84]:
parameters

{'W1': array([[0.26582211, 0.62038932],
        [0.25889916, 0.79857807]]),
 'b1': array([[0.42111308],
        [0.        ]]),
 'W2': array([[0.17805794],
        [0.46589499]]),
 'b2': array([[0.47953544]])}

In [44]:
import tensorflow
from tensorflow.keras import Sequential
from tensorflow import keras
from tensorflow.keras.layers import Dense, Flatten
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [45]:
model = Sequential()

model.add(Dense(2,activation="linear",input_dim=2))
model.add(Dense(1,activation="linear"))

d:\Education\Extra\Artificial Intelligence\Deep-Learning\.venv_tf312\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [46]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [47]:
model.get_weights()

[array([[-0.7573494 , -0.8532647 ],
        [ 0.67571497,  0.20743644]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.52054054],
        [ 0.943082  ]], dtype=float32),
 array([0.], dtype=float32)]

In [48]:
new_weights = [np.array([[0.1 , 0.1],[0.1 , 0.1]], dtype= np.float32),
    np.array([0 , 0], dtype= np.float32),
    np.array([[0.1],[0.1]], dtype= np.float32),
    np.array([0 ], dtype= np.float32)]

In [49]:
new_weights

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [50]:
model.set_weights(new_weights)

In [51]:
optimizer = keras.optimizers.Adam(learning_rate= 0.001)
model.compile(loss="binary_crossentropy",optimizer=optimizer)
model.fit(df.iloc[:,0:-1].values , df["is_placed"].values, epochs = 75, verbose=1, batch_size= 1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.7190
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7079 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6942 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6826 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6774
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6707
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6662 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6532 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6536 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6409 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6428 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6326 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6293 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6325 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6233
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━

In [97]:
model.get_weights()

[array([[0.37365356, 0.37365356],
        [0.36547363, 0.36547363]], dtype=float32),
 array([0.27226415, 0.27226415], dtype=float32),
 array([[0.3728561],
        [0.3728561]], dtype=float32),
 array([0.20467512], dtype=float32)]